spring:
  r2dbc:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5432/discount
    username: postgres
    password: Vaifery111
  application:
    name: discount

server:
  port: 7005